name: Lint

on:
  push:
    branches: [ main ]
  pull_requests:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: make setup-dev
      - run: make style
